config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :sessions => 'users/sessions'   
  } 
  devise_scope :user do
    get "sign_out", :to => "users/sessions#destroy" 
    get "users_delete", :to => "users/registrations#destroy" 
  end
  root to: 'app#new' 
  resources :app, only: [:new]
  resources :users, only: [:show]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    @like.save
    if @like.save
      redirect_to post_path(@like.post), notice: "いいねしました" 
    end
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    if @like.destroy
      redirect_to post_path(@like.post), notice: "いいねを取り消しました" 
    end
  end  
  
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
.like-link{:id => "like-link-#{post.id}"}
  - if current_user.likes.find_by(post_id: post.id)
    = link_to unlike_path(post.id), method: :delete, remote: true do
      .iine__button
        ❤️#{post.likes.count}
  - else
    = link_to like_path(post.id), method: :post, remote: true do
      .iine__button
        ♡️#{post.likes.count} %>


<div class="like-link" id="like-link-<%= @post.id %>">
  <% if current_user.likes.find_by(post_id: @post.id) %>
    <%= link_to unlike_path(@post.id), method: :delete, remote: true do %>
        <div class = "iine__button">❤️<%= @post.likes.count %></div>
    <% end %>
  <% else %>
    <%= link_to like_path(@post.id), method: :post, remote: true do %>
        <div class = "iine__button">♡️<%= @post.likes.count %></div>
    <% end %>
  <% end %>
</div>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/index.html.haml
-# !!!
-# %html{:lang => "ja"}
-#   %head
-#     %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
-#     %meta{:charset => "UTF-8"}/
-#     %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
-#     %title Document
-#     %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css", :integrity => "sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh", :rel => "stylesheet"}/
-#     = stylesheet_link_tag    'application', media: 'all'
-#     = stylesheet_link_tag    'likes.index', media: 'all'
    
-#   %body
-#     .main
-#       .container-fluid
-#         .likes-index
-#           %table.table.table-hover
-#             - @user.liked_posts.each do |post|
-#               %tr{:style=>"height: 80px;"}
-#                 %td.like
-#                   %i.fas.fa-heart
-#                   = post.likes.count
-#                 %td
-#                   = link_to "#{post.shopname}", post_path(post)
-#                 %td.sender
-#                   = "by▶︎#{post.user.nickname}"
-#                   %br
-#                     = post.created_at.strftime("%Y/%m/%d %H:%M")

-#         .pages
-#           = paginate(@posts)
            
-#       %script{:type => "module", :crossorigin => "anonymous", :integrity => "sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n", :src => "https://code.jquery.com/jquery-3.4.1.slim.min.js"}
-#       %script{:type => "module", :crossorigin => "anonymous", :integrity => "sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo", :src => "https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"}
-#       %script{:type => "module", :crossorigin => "anonymous", :integrity => "sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"}

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", post: @post  )) %>');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", post: @post  )) %>');