config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :sessions => 'users/sessions'   
  } 
  devise_scope :user do
    get "sign_out", :to => "users/sessions#destroy" 
    get "users_delete", :to => "users/registrations#destroy" 
  end
  root to: 'app#new' 
  resources :app, only: [:new]
  resources :users, only: [:show]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :shopname, presence: true
  validates :view, presence: true
  validates :content, presence: true

  belongs_to :user
  has_many :comments, foreign_key: :post_id, dependent: :destroy
  has_many :likes,    foreign_key: :post_id, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  mount_uploader :image, ImageUploader

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_group
  before_action :move_to_index
  before_action :move_to_mypage, only: [:edit]

  def index
    @posts = Post.all.order("created_at DESC").page(params[:page]).per(5)
    @lastpost = Post.last
    @secondlastpost = Post.last(2)[0]
    @thirdlastpost = Post.last(3)[0]
    @fourthlastpost = Post.last(4)[0]
    @fifthlastpost = Post.last(5)[0]
    @sixthlastpost = Post.last(6)[0]
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to posts_path, notice: "投稿できました" 
    else
      flash.now[:alert] = '足りない項目を入力してください'
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user).all.order("created_at DESC").page(params[:page]).per(5)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)

    if @post.save
      redirect_to post_path(@post), notice: "投稿を編集できました" 
    else
      flash.now[:alert] = '足りない項目を入力してください'
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path, notice: "削除しました"
  end

  private

  def post_params
    params.require(:post).permit(:shopname, :view, :image, :content, :image_cache).merge(user_id: current_user.id)
  end

  def set_group
    @user = User.find_by(params[:user_id])
  end

  def move_to_index
    redirect_to root_path unless user_signed_in?
  end

  def move_to_mypage
    @post = Post.find(params[:id])
    redirect_to user_path(current_user) unless current_user.id == @post.user.id
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_posts.html.haml
= render 'likes/like', post: post

app/views/posts/edit.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GoFun
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = stylesheet_link_tag    'posts.edit', media: 'all'

.edit_area
  .about_page
    %i.icon.far.fa-edit
    %h.about_icon 投稿編集ページです。

  .edit-form
    = form_for [@post] do |f|
      .field
        = f.text_field :shopname, class: 'shopname', placeholder: 'お店の名前'
      .field
        = f.text_field :view, class: 'view', placeholder: 'ストリートビュー'
      .file-field
        = f.label :image, class: 'form__mask__image' do
          = icon('fas', 'image', class: 'icon')
          = f.file_field :image, class: 'hidden'
      .field
        = f.text_area :content, class: 'content', placeholder: 'お店に行った感想など自由に書いてください', rows: "10"
      .field
        = f.submit '上書きする', class: 'form__submit'

  .destroy
    = button_to '投稿を削除', "/posts/#{@post.id}", method: :delete, data: { confirm: '投稿を削除してよろしいですか？' }

app/views/posts/index.html.haml
!!!
%html{:lang => "ja"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "UTF-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title Document
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css", :integrity => "sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all'
    = stylesheet_link_tag    'posts.index', media: 'all'
    
  %body
    .main
      .container-fluid
        #carousel-card.carousel.slide{"data-interval" => "4000", "data-ride" => "carousel"}

          .carousel-inner      
            %i.icon_about_slide.fas.fa-sync.fa-spin
            %h.desc_about_slide 最新6投稿のスライドです。
            .carousel-item.px-5.mt-5.active
              .row
                .card-wrap.card-pc.col-4
                  -if @posts.count >= 1
                    .index-heart-wrap
                      %i.heart.fas.fa-heart
                      = "#{@lastpost.likes.count}"
                    .card
                      %a{:href => "/posts/#{@lastpost.id}"}
                        .iframe-card-wrap
                          -if @lastpost.image?
                            %img{:allowfullscreen => "", :frameborder => "0", :height => "400px", :src => "#{@lastpost.image}", :width => "400px"}
                          -else 
                            %img{alt: "写真", height: "400px", src: "/images/no_image.jpg", width: "400px"}
                  -else
                    %p まだ投稿がありません
                    %img{alt: "写真", height: "400px", src: "/images/no_image.jpg", width: "400px"}

                .card-wrap.card-pc.col-4
                  -if @posts.count >= 2
                    .index-heart-wrap
                      %i.heart.fas.fa-heart
                      = "#{@secondlastpost.likes.count}"
                    .card
                      %a{:href => "/posts/#{@secondlastpost.id}"}
                        .iframe-card-wrap
                          -if @secondlastpost.image?
                            %img{:allowfullscreen => "", :frameborder => "0", :height => "400px", :src => "#{@secondlastpost.image}", :width => "400px"}
                          -else 
                            %img{alt: "写真", height: "400px", src: "/images/no_image.jpg", width: "400px"}
                  -else
                    %p まだ投稿がありません
                    %img{alt: "写真", height: "400px", src: "/images/no_image.jpg", width: "400px"}

                .card-wrap.card-pc.col-4
                  -if @posts.count >= 3
                    .index-heart-wrap
                      %i.heart.fas.fa-heart
                      = "#{@thirdlastpost.likes.count}"
                    .card
                      %a{:href => "/posts/#{@thirdlastpost.id}"}
                        .iframe-card-wrap
                          -if @thirdlastpost.image?
                            %img{:allowfullscreen => "", :frameborder => "0", :height => "400px", :src => "#{@thirdlastpost.image}", :width => "400px"}
                          -else 
                            %img{alt: "写真", height: "400px", src: "/images/no_image.jpg", width: "400px"}
                  -else
                    %p まだ投稿がありません
                    %img{alt: "写真", height: "400px", src: "/images/no_image.jpg", width: "400px"}
              
            .carousel-item.px-5.mt-5
              .row
                .card-wrap.card-pc.col-4
                  -if @posts.count >= 4
                    .index-heart-wrap
                      %i.heart.fas.fa-heart
                      = "#{@fourthlastpost.likes.count}"
                    .card
                      %a{:href => "/posts/#{@fourthlastpost.id}"}
                        .iframe-card-wrap
                          -if @fourthlastpost.image?
                            %img{:allowfullscreen => "", :frameborder => "0", :height => "400px", :src => "#{@fourthlastpost.image}", :width => "400px"}
                          -else 
                            %img{alt: "写真", height: "400px", src: "/images/no_image.jpg", width: "400px"}
                  -else
                    %p まだ投稿がありません
                    %img{alt: "写真", height: "400px", src: "/images/no_image.jpg", width: "400px"}

                .card-wrap.card-pc.col-4
                  -if @posts.count >= 5
                    .index-heart-wrap
                      %i.heart.fas.fa-heart
                      = "#{@fifthlastpost.likes.count}"
                    .card
                      %a{:href => "/posts/#{@fifthlastpost.id}"}
                        .iframe-card-wrap
                          -if @fifthlastpost.image?
                            %img{:allowfullscreen => "", :frameborder => "0", :height => "400px", :src => "#{@fifthlastpost.image}", :width => "400px"}
                          -else 
                            %img{alt: "写真", height: "400px", src: "/images/no_image.jpg", width: "400px"}
                  -else
                    %p まだ投稿がありません
                    %img{alt: "写真", height: "400px", src: "/images/no_image.jpg", width: "400px"}

                .card-wrap.card-pc.col-4
                  -if @posts.count >= 6
                    .index-heart-wrap
                      %i.heart.fas.fa-heart
                      = "#{@sixthlastpost.likes.count}"
                    .card
                      %a{:href => "/posts/#{@sixthlastpost.id}"}
                        .iframe-card-wrap
                          -if @sixthlastpost.image?
                            %img{:allowfullscreen => "", :frameborder => "0", :height => "400px", :src => "#{@sixthlastpost.image}", :width => "400px"}
                          -else 
                            %img{alt: "写真", height: "400px", src: "/images/no_image.jpg", width: "400px"}
                  -else
                    %p まだ投稿がありません
                    %img{alt: "写真", height: "400px", src: "/images/no_image.jpg", width: "400px"}

          %a.carousel-control-prev{"data-slide" => "prev", :href => "#carouselExampleFade", :role => "button"}
            %span.carousel-control-prev-icon{"aria-hidden" => "true"}
            %span.sr-only Previous
          %a.carousel-control-next{"data-slide" => "next", :href => "#carouselExampleFade", :role => "button"}
            %span.carousel-control-next-icon{"aria-hidden" => "true"}
            %span.sr-only Next

        .posts-index
          %i.icon_about_index.far.fa-comment-dots
          %h.desc_about_index 投稿一覧
          %table.table.table-hover
            - @posts.each do |post|
              %tr{:style=>"height: 80px;"}
                %td.like
                  %i.fas.fa-heart
                  = post.likes.count
                %td
                  = link_to "#{post.shopname}", post_path(post)
                %td.sender
                  = "by▶︎#{post.user.nickname}"
                  %br
                    = post.created_at.strftime("%Y/%m/%d %H:%M")

        .pages
          = paginate(@posts)
            
      %script{:type => "module", :crossorigin => "anonymous", :integrity => "sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n", :src => "https://code.jquery.com/jquery-3.4.1.slim.min.js"}
      %script{:type => "module", :crossorigin => "anonymous", :integrity => "sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo", :src => "https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"}
      %script{:type => "module", :crossorigin => "anonymous", :integrity => "sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"}

app/views/posts/new.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Gohan2
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = stylesheet_link_tag    'posts.new', media: 'all'
    = javascript_include_tag 'application'

.main
  .form
    .about_page
      %i.icon.far.fa-paper-plane
      %h.about_icon 新規投稿ページです。

    = form_for [@post] do |f|
      = f.text_field :shopname, class: 'shopname', placeholder: 'お店の名前'
      = f.text_area :view, class: 'view', placeholder: '共有したいGoogleストリートビューの"共有"ボタンから埋め込み用HTMLを確認してこちらに貼ってみましょう。&#13;&#10;例）<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12967.0806533878!2d139.7016358!3d35.6580339!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x337328def1e2ab26!2z5riL6LC36aeF!5e0!3m2!1sja!2sjp!4v1589774591958!5m2!1sja!2sjp" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>'.html_safe
      = f.file_field :image, class: 'image', placeholder: '画像'
      = f.hidden_field :image_cache
      = f.text_area :content, class: 'content', placeholder: 'お店に行った感想など自由に書いてみましょう', rows: "3"
      = f.submit '投稿する', class: 'form__submit'

app/views/posts/show.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GoFun
    = csrf_meta_tags
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css", :integrity => "sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all'
    = stylesheet_link_tag    'posts.show', media: 'all'
    = javascript_include_tag 'application'

.wrapper
  .images
    .view
      %iframe{:height => "100%", :width => "300%", :src => "#{@post.view.gsub(/<iframe src="/,'').gsub(/" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0">/,'').gsub(/<iframe src="/,'')}"}     
    .post__image
      %img{:allowfullscreen => "", :frameborder => "0", :height => "500px", :src => "#{@post.image}", :width => "500px"}

  .chat-area
    .post-side
      .post-side__title
        .post-side__title__likes
          - if current_user.already_liked?(@post)
            = button_to post_like_path(@post), class:"like_selsect", method: :delete do
              %i.like.fas.fa-heart
              = "#{@post.likes.count}　　#{@post.shopname}"
          - else
            = button_to post_likes_path(@post), class:"like_selsect" do
              %i.dislike.far.fa-heart
              = "#{@post.likes.count}　　#{@post.shopname}"
      
      .post-side__content
        = @post.content

      .post-side__sender
        .post-side__sender__info
          .post-side__sender__info__image
            - if @post.user.image?
              = link_to image_tag("#{@post.user.image}", alt: "アイコン", width: "70px", height: "70px"), user_path(@post.user)
            - else
              = link_to image_tag("/images/no_image.jpg", alt: "アイコン", width: "70px"), user_path(@post.user)
          .post-side__sender__info__nickname
            = @post.user.nickname
          = @post.created_at.strftime("%Y/%m/%d %H:%M")
      .post-side__edit
        - if current_user.id == @post.user.id
          %a.btn{"aria-label" => "Edit", :href => "/posts/#{@post.id}/edit"}
            %i.far.fa-edit{"aria-hidden" => "true", :title => "この投稿を編集しますか？"}
            %h.about_delete_button 投稿編集
      .post-side__liked-user
        いいねしたユーザー▶︎
        - @post.liked_users.each do |user|
          - if user.image?
            = link_to image_tag("#{user.image}", alt: "アイコン", width: "70px", height: "70px", :title => "#{user.nickname}"), user_path(user)
          - else
            = link_to image_tag("/images/no_image.jpg", alt: "アイコン", width: "70px", :title => "#{user.nickname}"), user_path(user)

    .comment-side
      .comment-side__form
        = form_for [@post, @comment] do |f|
          = f.text_area :content, class: 'form__message', placeholder: 'コメントを送ってみましょう'
          = f.submit 'コメントする', class: 'form__submit'

      .comment-side__#index
        %i.comments.far.fa-comments
        %table.table.table-hover
          - @comments.each do |comment|
            %tr
              %td
                %p
                  = comment.content

              %td.sender
                - if comment.user.image?
                  = link_to image_tag("#{comment.user.image}", alt: "アイコン", width: "70px", height: "70px"), user_path(comment.user)
                - else
                  = link_to image_tag("/images/no_image.jpg", alt: "アイコン", width: "70px"), user_path(comment.user)
                
                %p.sender_name
                  = "#{comment.user.nickname}"
              
                .delete_button
                  - if current_user.id == comment.user.id
                    = button_to '削除', "/posts/#{comment.post.id}/comments/#{comment.id}", method: :delete, data: { confirm: 'コメントを削除してよろしいですか？' }
                  .send_date
                    = comment.created_at.strftime("%Y/%m/%d %H:%M")

        .pages
          = paginate(@comments)
  
      %script{:type => "module", :crossorigin => "anonymous", :integrity => "sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n", :src => "https://code.jquery.com/jquery-3.4.1.slim.min.js"}
      %script{:type => "module", :crossorigin => "anonymous", :integrity => "sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo", :src => "https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"}
      %script{:type => "module", :crossorigin => "anonymous", :integrity => "sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"}